// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EngineController from "./engine_controller.js"
application.register("engine", EngineController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import NewValveAdjustmentController from "./new_valve_adjustment_controller.js"
application.register("new-valve-adjustment", NewValveAdjustmentController)

import ShimController from "./shim_controller.js"
application.register("shim", ShimController)

import TokenController from "./token_controller.js"
application.register("token", TokenController)

import ValveAdjustmentController from "./valve_adjustment_controller.js"
application.register("valve-adjustment", ValveAdjustmentController)

import ValveGapsController from "./valve_gaps_controller.js"
application.register("valve-gaps", ValveGapsController)
