version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: shimsuser
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - shims-postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    links:
      - postgres
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/opt/app
      - node-modules:/opt/node_modules
    command: ./bin/docker_entrypoint.sh
  sidekiq:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    links:
      - postgres
      - redis
    command: bundle exec sidekiq
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - web
    depends_on:
      - web
    ports:
      - '80:80'
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - shims-redis:/var/lib/redis/data
volumes:
  shims-postgres:
  shims-redis:
  node-modules: