version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: shimsuser
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - shims-postgres:/var/lib/postgresql/data
  web:
    image: motorcycleshims/web:production
    links:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env
    tty: true
    volumes:
      - .:/opt/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/opt/app/node_modules
    entrypoint: ./entrypoint.sh
volumes:
  shims-postgres:
  gem_cache:
  node_modules: